Repository restarone/violet_rails, pull requests merged in 2022-10, with the labels that each got.

#1140 [feature] Allow active support / view helpers in API Renderer. (#1136)
  app/models/concerns/dynamic_attribute.rb
  test/helpers/content_helper_test.rb
Labels: Pending UAT on Staging :red_circle:

#1142 [feature] Allow active support / view helpers in API Renderer
  app/models/concerns/dynamic_attribute.rb
  test/helpers/content_helper_test.rb
Labels: release-candidate

#1146 [feature] API resource query match any one condition (#1145)
  app/helpers/content_helper.rb
  app/models/concerns/jsonb_search/query_builder.rb
  app/models/concerns/jsonb_search/searchable.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: Passing UAT on Heroku :white_check_mark:

#1148 [feature] API resource query match any one condition (#1145) (#1146)
  app/helpers/content_helper.rb
  app/models/concerns/jsonb_search/query_builder.rb
  app/models/concerns/jsonb_search/searchable.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: Pending UAT on Staging :red_circle:

#1143 [feature] Unique string aggregator plugin (#1133)
  test/fixtures/api_namespaces.yml
  test/fixtures/external_api_clients.yml
  test/plugins/unique_string_aggregator_plugin_test.rb
Labels: Pending UAT on Heroku :warning:, Pending UAT on Staging :red_circle:

#1150 [feature] Unique string aggregator plugin (#1133) (#1143)
  test/fixtures/api_namespaces.yml
  test/fixtures/external_api_clients.yml
  test/plugins/unique_string_aggregator_plugin_test.rb
Labels: Pending UAT on Staging :red_circle:

#1121 Transcript parser plugin
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/fixtures/external_api_clients.yml
  test/plugins/transcript_parser_plugin_test.rb
Labels: Pending UAT on Heroku :warning:

#1151 [feature] Transcript parser plugin (#1121)
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/fixtures/external_api_clients.yml
  test/plugins/transcript_parser_plugin_test.rb
Labels: Pending UAT on Staging :red_circle:

#1158 [feature] enforce loading assets over https
  config/initializers/force_ssl.rb
Labels: Passing UAT on Staging :white_check_mark:, Passing UAT on Heroku :white_check_mark:

#1176 [bug fix] resolve API resource query error when apostrophe (') is included
  app/models/concerns/jsonb_search/query_builder.rb
  test/helpers/content_helper_test.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: Passing UAT on Heroku :white_check_mark:

#1177 [bug fix] resolve API resource query error when apostrophe (') is included
  app/models/concerns/jsonb_search/query_builder.rb
  test/helpers/content_helper_test.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: Pending UAT on Staging :red_circle:

#1179 [feature] Dokku integration for testnet (#1172)
  .buildpacks
  .github/workflows/dokku-deploy.yml
  Procfile
  bin/ci-pre-deploy
Labels: Pending UAT on Staging :red_circle:

#1103 [feature] allow access to API by category
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/comfy/admin/api_clients_controller.rb
  app/controllers/comfy/admin/api_forms_controller.rb
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/controllers/comfy/admin/external_api_clients_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/models/user.rb
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/users/_api_accessibility.haml
  app/views/comfy/admin/users/_form.haml
  app/views/comfy/admin/users/index.html.haml
  config/routes.rb
  db/migrate/20220913021415_add_api_accessibility_to_users.rb
  db/migrate/20220917134117_remove_can_manage_api_from_users_and_back_fill_api_accessibility.rb
  db/schema.rb
  test/controllers/admin/comfy/api_actions_controller_test.rb
  test/controllers/admin/comfy/api_clients_controller_test.rb
  test/controllers/admin/comfy/api_forms_controller_test.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
Labels: early-alpha UNSAFE

#1153 [feature] 2FA + ability to enforce 2FA at the subdomain level
  .env.test
  .github/workflows/ruby.yml
  Gemfile
  Gemfile.lock
  app/controllers/comfy/admin/web_settings_controller.rb
  app/controllers/concerns/twofactor_authenticable.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/mailers/user_mailer.rb
  app/models/subdomain.rb
  app/models/user.rb
  app/views/comfy/admin/web_settings/_form.haml
  app/views/user_mailer/send_otp.html.erb
  app/views/users/invitations/edit.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/sessions/new.html.haml
  app/views/users/sessions/two_factor.html.erb
  app/views/users/shared/error.js.erb
  app/views/users/shared/otp_visible.js.erb
  config/initializers/devise.rb
  config/routes.rb
  config/secrets.yml
  db/migrate/20221010090227_add_devise_two_factor_to_users.rb
  db/migrate/20221010105643_add_enable_2fa_to_subdomains.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users/registrations_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/mailers/user_mailer_test.rb
  test/models/subdomain_test.rb
Labels: enhancement, high priority

#1174 [Feature] Social Sharing Metadata Option in API Namespace
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/helpers/content_helper.rb
  app/helpers/subdomain_helper.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/shared/_meta_tags.html.erb
  config/routes.rb
  db/migrate/20221025091924_add_metadata_to_api_namespaces.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/helpers/subdomain_helper_test.rb
Labels: enhancement
