Repository restarone/violet_rails, pull requests merged in 2022-07, with the labels that each got.

#855 [Bug fix] Devise login forms do not show correct error messages
  config/initializers/active_support.rb
  config/initializers/devise.rb
  test/controllers/users/registrations_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
Labels: staging

#853 [feature] ability to toggle trix editor attachments
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/non_primitive_property.rb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/non_primitive_properties/_nested_form.haml
  db/migrate/20220628050113_add_allow_attachments_to_non_primitive_properties.rb
  db/schema.rb
  test/models/non_primitive_property_test.rb
Labels: early-alpha UNSAFE

#784 [feature] Dynamic attributes in API Actions
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/mailers/api_action_mailer.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/models/concerns/safe_executable_validator.rb
  app/views/api_action_mailer/send_email.html.erb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_actions/index.html.haml
  app/views/comfy/admin/api_actions/show.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  app/views/comfy/admin/external_api_clients/index.html.haml
  config/environments/development.rb
  db/migrate/20220609092515_add_email_subject_to_api_actions.rb
  db/schema.rb
  test/models/api_action_test.rb
  test/models/concerns/dynamic_attribute_test.rb
  test/models/external_api_client_test.rb
Labels: API - data pipeline v3, heroku-ready

#866 [feature] Dynamic attributes in API Actions
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/mailers/api_action_mailer.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/models/concerns/safe_executable_validator.rb
  app/views/api_action_mailer/send_email.html.erb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_actions/index.html.haml
  app/views/comfy/admin/api_actions/show.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  app/views/comfy/admin/external_api_clients/index.html.haml
  config/environments/development.rb
  db/migrate/20220609092515_add_email_subject_to_api_actions.rb
  db/schema.rb
  test/models/api_action_test.rb
  test/models/concerns/dynamic_attribute_test.rb
  test/models/external_api_client_test.rb
Labels: staging

#859 [feature] ability to toggle trix editor attachments
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/non_primitive_properties/_nested_form.haml
  db/migrate/20220628050113_add_allow_attachments_to_non_primitive_properties.rb
  db/schema.rb
  test/models/non_primitive_property_test.rb
Labels: heroku-ready

#885 [bug fix] handle textarea overflow in send_email API action
  app/views/comfy/admin/api_actions/_form.html.haml
Labels: heroku-ready

#772 [Violet Rails Core]: Pass current user and current visit to api data pipeline
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/models/current.rb
  app/views/comfy/admin/api_actions/show.html.haml
  test/controllers/resource_controller_test.rb
Labels: API - data pipeline v3, early-alpha UNSAFE

#898 [feature] ability to have an email signature + name in email
  app/controllers/comfy/admin/web_settings_controller.rb
  app/mailboxes/e_mailbox.rb
  app/mailers/e_mailer.rb
  app/models/subdomain.rb
  app/views/comfy/admin/cms/partials/_navigation_inner.haml
  app/views/comfy/admin/users/index.html.haml
  app/views/comfy/admin/web_settings/_form.haml
  app/views/e_mailer/ship.html.erb
  config/locales/views/comfy/web_settings/en.yml
  db/migrate/20220709172402_add_email_name_and_signature_to_subdomains.rb
  db/schema.rb
  test/controllers/admin/comfy/users_controller_test.rb
  test/fixtures/files/email_with_multiple_recipients.eml
  test/mailboxes/e_mailbox_test.rb
Labels: staging

#892 [feature] Pass current user and current visit to api data pipeline
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/models/current.rb
  app/views/comfy/admin/api_actions/show.html.haml
  test/controllers/resource_controller_test.rb
Labels: high priority, API - data pipeline v3, heroku-ready

#887 [feature] Allow dynamic segment in api redirect action
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_actions/show.html.haml
  db/migrate/20220707090412_add_redirect_type_to_api_actions.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
Labels: high priority, API - data pipeline v3, heroku-ready

#918 [feature] Allow dynamic segment in API redirect action
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_actions/show.html.haml
  db/migrate/20220707090412_add_redirect_type_to_api_actions.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
Labels: staging

#913 [feature] Pass current user and current visit to API data pipeline
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/concerns/dynamic_attribute.rb
  app/models/current.rb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_actions/show.html.haml
  test/controllers/resource_controller_test.rb
Labels: heroku-ready

#933 [bug fix] resolve test coverage of models reports 0% (#929)
  ci_env.cfg
  run_tests.sh
  test/test_helper.rb
Labels: staging

#664 [feature] custom API Actions
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/comfy/admin/cms.js
  app/models/api_action.rb
  app/models/custom_api_action.rb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_actions/show.html.haml
  db/migrate/20220521032523_add_method_definition_to_api_actions.rb
  db/schema.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/resource_controller_test.rb
  test/fixtures/api_actions.yml
  test/fixtures/api_forms.yml
  test/fixtures/api_namespaces.yml
  test/models/api_action_test.rb
Labels: heroku-ready

#945 [feature] show dynamic attributes in API Resources index table
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: heroku-ready

#940 attach current_visit and current_user to created API Resource (#939)
  app/controllers/concerns/api_actionable.rb
  app/helpers/ahoy_events_helper.rb
  app/models/ahoy/event.rb
  app/models/api_resource.rb
  app/views/comfy/admin/api_resources/show.html.haml
  test/controllers/resource_controller_test.rb
  test/helpers/ahoy_events_helper_test.rb
  test/models/api_resource_test.rb
Labels: heroku-ready

#971 [Bug fix]: can't delete user if they have forum post subscriptions
  app/helpers/ahoy_events_helper.rb
  app/helpers/simple_discussion/forum_posts_helper.rb
  app/models/forum_post.rb
  app/models/forum_thread.rb
  app/models/user.rb
  app/views/comfy/admin/users/_form.haml
  app/views/simple_discussion/forum_posts/_forum_post.html.erb
  app/views/simple_discussion/forum_threads/_forum_thread.html.erb
  app/views/simple_discussion/forum_threads/show.html.erb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/simple_discussion/forum_threads_controller_test.rb
  test/helpers/ahoy_events_helper_test.rb
Labels: heroku-ready

#973 [Bug fix]: can't delete user if they have forum post subscriptions
  app/helpers/ahoy_events_helper.rb
  app/helpers/simple_discussion/forum_posts_helper.rb
  app/models/forum_post.rb
  app/models/forum_thread.rb
  app/models/user.rb
  app/views/comfy/admin/users/_form.haml
  app/views/simple_discussion/forum_posts/_forum_post.html.erb
  app/views/simple_discussion/forum_threads/_forum_thread.html.erb
  app/views/simple_discussion/forum_threads/show.html.erb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/simple_discussion/forum_threads_controller_test.rb
  test/helpers/ahoy_events_helper_test.rb
Labels: release-candidate

#968 [Feature] return non primitive types in REST API and GraphQL response
  app/graphql/types/api_resource_type.rb
  app/graphql/types/non_primitive_property_type.rb
  app/models/non_primitive_property.rb
  app/serializers/api_resource_serializer.rb
  app/serializers/non_primitive_property_serializer.rb
  test/controllers/api/resource_controller_test.rb
  test/controllers/graphql_controller_test.rb
Labels: early-alpha UNSAFE

#959 [Feature] Allow querying in REST API and GraphQL
  app/controllers/api/resource_controller.rb
  app/graphql/types/api_namespace_type.rb
  app/models/api_resource.rb
  app/models/concerns/jsonb_search/query_builder.rb
  app/models/concerns/jsonb_search/searchable.rb
  test/controllers/api/resource_controller_test.rb
  test/controllers/graphql_controller_test.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: early-alpha UNSAFE

#993 [Feature] Allow querying in REST API and GraphQL
  app/controllers/api/resource_controller.rb
  app/graphql/types/api_namespace_type.rb
  app/models/api_resource.rb
  app/models/concerns/jsonb_search/query_builder.rb
  app/models/concerns/jsonb_search/searchable.rb
  test/controllers/api/resource_controller_test.rb
  test/controllers/graphql_controller_test.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: Passing UAT on Heroku :white_check_mark:

#992 [Bug Fix] Silent recaptcha with challenge if confidence is low
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/shared/fallback_to_recaptcha_v2.js.erb
  test/controllers/resource_controller_test.rb
Labels: high priority

#995 [Feature] Allow querying in REST API and GraphQL
  app/controllers/api/resource_controller.rb
  app/graphql/types/api_namespace_type.rb
  app/models/api_resource.rb
  app/models/concerns/jsonb_search/query_builder.rb
  app/models/concerns/jsonb_search/searchable.rb
  test/controllers/api/resource_controller_test.rb
  test/controllers/graphql_controller_test.rb
  test/models/concerns/jsonb_search/query_builder_test.rb
Labels: Passing UAT on Staging :white_check_mark:

#996 [Bug Fix] Silent recaptcha with challenge if confidence is low
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/shared/fallback_to_recaptcha_v2.js.erb
  test/controllers/resource_controller_test.rb
Labels: Passing UAT on Heroku :white_check_mark:
