Repository restarone/violet_rails, pull requests merged in 2022-06, with the labels that each got.

#680 [feature] Ability to delete custom event and visits, [feature] add code editor to ExternalApiConnection
  app/controllers/comfy/admin/dashboard_controller.rb
  app/models/ahoy/event.rb
  app/views/comfy/admin/dashboard/events_detail.haml
  app/views/comfy/admin/external_api_clients/_form.html.haml
  config/environments/production.rb
  config/environments/staging.rb
  config/routes.rb
  test/controllers/admin/comfy/dashboard_controller_test.rb
Labels: production ready

#689 [feature] add permission can_manage_files to decouple can_manage_web from file system access
  app/controllers/comfy/admin/cms/files_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/models/user.rb
  app/views/comfy/admin/users/_form.haml
  config/initializers/comfortable_mexican_sofa.rb
  db/migrate/20220606015014_add_can_manage_files_to_users.rb
  db/schema.rb
  test/controllers/admin/comfy/pages_controller_test.rb
  test/controllers/comfy/admin/cms/files_controller_test.rb
Labels: WIP

#686 [bug fix] remove 12 factor gem that was preventing logging on ec2, [feature] Change scoping of api clients and redirection after api resource is deleted, [bug fix] fix data discovery issue for ExternalApiClient in rake tasks (public schema is not being read), [feature] add permission can_manage_files to decouple can_manage_web from file system access
  Gemfile
  Gemfile.lock
  app/controllers/comfy/admin/api_clients_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/controllers/comfy/admin/cms/files_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/models/user.rb
  app/views/comfy/admin/api_resources/edit.html.haml
  app/views/comfy/admin/api_resources/index.html.haml
  app/views/comfy/admin/api_resources/index.json.jbuilder
  app/views/comfy/admin/api_resources/new.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  app/views/comfy/admin/users/_form.haml
  config/initializers/comfortable_mexican_sofa.rb
  config/routes.rb
  db/migrate/20220606015014_add_can_manage_files_to_users.rb
  db/schema.rb
  lib/tasks/external_api_client.rake
  test/controllers/admin/comfy/api_clients_controller_test.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/admin/comfy/pages_controller_test.rb
  test/controllers/comfy/admin/cms/files_controller_test.rb
Labels: staging, release-candidate

#702 [Violet Rails Core]: Recaptcha v3 option in api form
  app/controllers/comfy/admin/api_forms_controller.rb
  app/controllers/resource_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/comfy/admin/cms.js
  app/javascript/packs/website/call_to_actions.js
  app/models/api_form.rb
  app/views/comfy/admin/api_forms/_form.html.haml
  app/views/comfy/admin/api_forms/_render.haml
  db/migrate/20220609041057_add_show_recaptcha_v3_to_api_forms.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/helpers/application_helper_test.rb
  test/models/api_form_test.rb
Labels: heroku-ready

#712 [feature] sanitize method/model definitions coming into Violet Rails of things like: Subdomain, Apartment, Tenant, switch, SomeModel.destroy_all, SomeModel.update_all, global_admin, can_manage_users
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/api_action.rb
  app/models/concerns/safe_executable_validator.rb
  app/models/external_api_client.rb
  test/fixtures/external_api_clients.yml
  test/models/external_api_client_test.rb
Labels: staging, release-candidate

#626 [Bug fix] last admin should not be able to delete themselves
  app/models/user.rb
  app/views/comfy/admin/users/_form.haml
  test/controllers/admin/comfy/users_controller_test.rb
  test/models/user_test.rb
Labels: early-alpha UNSAFE

#718 [Bug fix] last admin should not be able to delete themselves
  app/models/user.rb
  app/views/comfy/admin/users/_form.haml
  test/controllers/admin/comfy/users_controller_test.rb
  test/models/user_test.rb
Labels: heroku-ready

#722 Js deps upgrade jun 10 2022
  yarn.lock
Labels: heroku-ready

#724 Js deps upgrade jun 10 2022 (#722)
  yarn.lock
Labels: staging

#727 Ruby deps upgrade june 10 2022 (#725)
  Gemfile.lock
Labels: staging

#709 [feature]: Recaptcha v3 option in API form (#702)
  app/controllers/comfy/admin/api_forms_controller.rb
  app/controllers/resource_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/comfy/admin/cms.js
  app/javascript/packs/website/call_to_actions.js
  app/models/api_form.rb
  app/views/comfy/admin/api_forms/_form.html.haml
  app/views/comfy/admin/api_forms/_render.haml
  db/migrate/20220609041057_add_show_recaptcha_v3_to_api_forms.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/helpers/application_helper_test.rb
  test/models/api_form_test.rb
Labels: early-alpha UNSAFE

#732 [feature]: Recaptcha v3 option in API form (#702)
  app/controllers/comfy/admin/api_forms_controller.rb
  app/controllers/resource_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/comfy/admin/cms.js
  app/javascript/packs/website/call_to_actions.js
  app/models/api_form.rb
  app/views/comfy/admin/api_forms/_form.html.haml
  app/views/comfy/admin/api_forms/_render.haml
  db/migrate/20220609041057_add_show_recaptcha_v3_to_api_forms.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/helpers/application_helper_test.rb
  test/models/api_form_test.rb
Labels: staging

#733 [feature branch]: Support for node 10 and 14 (#730)
  .github/workflows/ruby.yml
  package.json
Labels: heroku-ready

#745 [CI] action to verify schema.rb integrity, [CI] Support for node 10 and 14 builds
  .github/workflows/ruby.yml
  package.json
  test/models/subdomain_test.rb
Labels: staging

#756 [feature] forum - show latest post in threads index (#755)
  app/views/simple_discussion/forum_threads/_forum_thread.html.erb
  test/controllers/simple_discussion/forum_threads_controller_test.rb
Labels: staging

#747 show privileges in users/index
  app/views/comfy/admin/users/index.html.haml
  test/controllers/admin/comfy/users_controller_test.rb
Labels: heroku-ready

#760 show privileges in users/index (#747)
  app/views/comfy/admin/users/index.html.haml
  test/controllers/admin/comfy/users_controller_test.rb
Labels: staging

#765 fix data discovery issue in rake tasks (public schema is not accessed)
  app/models/subdomain.rb
  lib/tasks/api_action.rake
  lib/tasks/external_api_client.rake
  lib/tasks/maintenance.rake
  lib/tasks/report.rake
Labels: staging

#766 allow multiple recipients for emails with select2
  app/controllers/mailbox/message_threads_controller.rb
  app/mailers/e_mailer.rb
  app/views/mailbox/message_threads/_form.haml
  test/mailers/e_mailer_test.rb
Labels: heroku-ready

#771 [CI] add tests for ExternalApiClientsController, [plugin] create VacuumJob plugin for ExternalApiClient/Connection
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/fixtures/external_api_clients.yml
Labels: staging

#795 [feature] add pagination + search to email threads/index
  app/controllers/mailbox/mailbox_controller.rb
  app/models/message.rb
  app/models/message_thread.rb
  app/views/mailbox/mailbox/_pagination.haml
  app/views/mailbox/mailbox/_search_filters.haml
  app/views/mailbox/mailbox/show.haml
  test/controllers/mailbox/mailbox_controller_test.rb
Labels: staging

#797 [CI] add matrix CI for Ruby 3 build, [deprecation] ember.js, [feature] Ruby 3 dev environment
  .github/workflows/ruby.yml
  .ruby-version
  Dockerfile.dev
  Gemfile
  Gemfile.lock
  config/initializers/ember.rb
  config/routes.rb
  test/integration/ember/ember_js_renderer_test.rb
Labels: early-alpha UNSAFE

#798 [CI] add matrix CI for Ruby 3 build, [deprecation] ember.js, [feature] Ruby 3 dev environment
  .github/workflows/ruby.yml
  .ruby-version
  Dockerfile.dev
  Gemfile
  Gemfile.lock
  config/initializers/ember.rb
  config/routes.rb
  test/integration/ember/ember_js_renderer_test.rb
Labels: staging

#806 revert ruby 3 docker dev, remove model filter from test coverage, when feature is un-enabled remove buttons related to it
  Dockerfile.dev
  app/views/comfy/admin/cms/partials/_navigation_before.haml
  app/views/comfy/admin/cms/partials/_navigation_inner.haml
  test/controllers/admin/comfy/users_controller_test.rb
  test/test_helper.rb
Labels: staging

#819 [feature] make server turbo native ready
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/views/layouts/comfy/blog/application.html.erb
  app/views/layouts/devise.html.haml
  app/views/layouts/simple_discussion.html.erb
Labels: staging

#834 [CI] Save code coverage as artifact
  .github/workflows/ruby.yml
Labels: staging

#821 [feature] export/import API Namespace with/without children in JSON format
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/api_namespace.rb
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/new.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  config/routes.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: heroku-ready
