Repository restarone/violet_rails, pull requests merged in 2022-12, with the labels that each got.

#1256 [feature] Ability to mention user in forum
  app/assets/stylesheets/actiontext.scss
  app/controllers/simple_discussion/application_controller.rb
  app/controllers/simple_discussion/forum_posts_controller.rb
  app/controllers/simple_discussion/forum_threads_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/tribute.js
  app/models/forum_post.rb
  app/models/forum_thread.rb
  app/models/user.rb
  app/views/simple_discussion/forum_posts/_form.html.erb
  app/views/simple_discussion/forum_threads/_form.html.erb
  app/views/users/_user.html.erb
  config/locales/en.yml
  package.json
  test/controllers/simple_discussion/forum_threads_controller_test.rb
  yarn.lock
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1261 [feature] Ability to mention user in forum (#1256)
  app/assets/stylesheets/actiontext.scss
  app/controllers/simple_discussion/application_controller.rb
  app/controllers/simple_discussion/forum_posts_controller.rb
  app/controllers/simple_discussion/forum_threads_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/tribute.js
  app/models/forum_post.rb
  app/models/forum_thread.rb
  app/models/user.rb
  app/views/simple_discussion/forum_posts/_form.html.erb
  app/views/simple_discussion/forum_threads/_form.html.erb
  app/views/users/_user.html.erb
  config/locales/en.yml
  package.json
  test/controllers/simple_discussion/forum_threads_controller_test.rb
  yarn.lock
Labels: Pending UAT on Staging :red_circle:

#1262 [feature] associate multiple snippets with API #show and #index
  app/helpers/content_helper.rb
  test/helpers/content_helper_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1267 [feature] associate multiple snippets with API #show and #index (#1262)
  app/helpers/content_helper.rb
  test/helpers/content_helper_test.rb
Labels: Pending UAT on Staging :red_circle:

#1266 [Bug Fix] cookie consent is popping up too often and is not persisted
  app/controllers/application_controller.rb
  app/controllers/concerns/ahoy_controller_patch.rb
  app/controllers/cookies_controller.rb
  app/views/comfy/admin/web_settings/_form.haml
  app/views/shared/_cookies_consent_ui.html.erb
  config/initializers/ahoy.rb
  config/routes.rb
  db/migrate/20221128055836_change_cookie_consent_ui_default_in_subdomain.rb
  db/schema.rb
  test/controllers/cookies_controller_test.rb
  test/controllers/disk_controller_test.rb
Labels: deploy-review-app

#1268 [Bug Fix] cookie consent is popping up too often
  app/controllers/application_controller.rb
  app/controllers/concerns/ahoy_controller_patch.rb
  app/controllers/cookies_controller.rb
  app/views/comfy/admin/web_settings/_form.haml
  app/views/shared/_cookies_consent_ui.html.erb
  config/initializers/ahoy.rb
  config/routes.rb
  db/migrate/20221128055836_change_cookie_consent_ui_default_in_subdomain.rb
  db/schema.rb
  test/controllers/cookies_controller_test.rb
  test/controllers/disk_controller_test.rb
Labels: Pending UAT on Staging :red_circle:

#1272 [bug fix]: undefined `cookies' for Api::ResourceController
  app/controllers/concerns/ahoy_controller_patch.rb
  test/controllers/api/resource_controller_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1273 [bug fix]: undefined `cookies' for Api::ResourceController
  app/controllers/concerns/ahoy_controller_patch.rb
  test/controllers/api/resource_controller_test.rb
Labels: Pending UAT on Staging :red_circle:

#1275 [bug fix] can't search by name in API #index
  app/models/api_namespace.rb
  app/views/comfy/admin/api_namespaces/_search_filters.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: deploy-review-app

#1279 [CI] Job to delete all review apps
  .github/workflows/dokku-clean-review-apps.yml
Labels: deploy-review-app

#1280 [CI] Job to delete all review apps (#1279)
  .github/workflows/dokku-clean-review-apps.yml
Labels: Pending UAT on Staging :red_circle:

#1181 [feature] allow access to API by category (#1103)
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/comfy/admin/api_clients_controller.rb
  app/controllers/comfy/admin/api_forms_controller.rb
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/controllers/comfy/admin/external_api_clients_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/helpers/api_accessibility_helper.rb
  app/models/api_namespace.rb
  app/models/user.rb
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/users/_api_accessibility.haml
  app/views/comfy/admin/users/_form.haml
  app/views/comfy/admin/users/index.html.haml
  config/routes.rb
  db/migrate/20220913021415_add_api_accessibility_to_users.rb
  db/migrate/20220917134117_remove_can_manage_api_from_users_and_back_fill_api_accessibility.rb
  db/schema.rb
  test/controllers/admin/comfy/api_actions_controller_test.rb
  test/controllers/admin/comfy/api_clients_controller_test.rb
  test/controllers/admin/comfy/api_forms_controller_test.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/helpers/api_accessibility_helper_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
Labels: Passing UAT on Testnet :white_check_mark:

#1282 [feature] allow access to API by category (#1103) (#1181)
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/comfy/admin/api_clients_controller.rb
  app/controllers/comfy/admin/api_forms_controller.rb
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/controllers/comfy/admin/external_api_clients_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/helpers/api_accessibility_helper.rb
  app/models/api_namespace.rb
  app/models/user.rb
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/users/_api_accessibility.haml
  app/views/comfy/admin/users/_form.haml
  app/views/comfy/admin/users/index.html.haml
  config/routes.rb
  db/migrate/20220913021415_add_api_accessibility_to_users.rb
  db/migrate/20220917134117_remove_can_manage_api_from_users_and_back_fill_api_accessibility.rb
  db/schema.rb
  test/controllers/admin/comfy/api_actions_controller_test.rb
  test/controllers/admin/comfy/api_clients_controller_test.rb
  test/controllers/admin/comfy/api_forms_controller_test.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/helpers/api_accessibility_helper_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
Labels: Pending UAT on Staging :red_circle:

#1287 [Bug Fix]: fix generated documentation in API Namespace
  app/helpers/api_namespaces_helper.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/api_namespaces.yml
  test/helpers/api_namespaces_helper_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1288 [Bug Fix] Video playback issue on Nikean story platform
  app/controllers/application_controller.rb
  app/helpers/content_helper.rb
  app/models/api_resource.rb
  app/models/current.rb
  app/models/non_primitive_property.rb
  app/sidekiq/fire_api_actions_job.rb
  config/initializers/active_storge.rb
  config/initializers/sidekiq.rb
Labels: deploy-review-app

#1291 [Bug Fix] serve long lived file URLs in renderer
  app/controllers/application_controller.rb
  app/helpers/content_helper.rb
  app/models/api_resource.rb
  app/models/current.rb
  app/models/non_primitive_property.rb
  app/sidekiq/fire_api_actions_job.rb
  config/initializers/active_storge.rb
  config/initializers/sidekiq.rb
Labels: Pending UAT on Staging :red_circle:

#1298 [bug fix] don't raise error when API Resource ID is bad
  app/helpers/content_helper.rb
  test/helpers/content_helper_test.rb
Labels: Pending UAT on Staging :red_circle:

#1299 [Bug Fix] resolve email threads
  app/mailboxes/e_mailbox.rb
  app/mailers/e_mailer.rb
  app/models/message.rb
  test/mailboxes/e_mailbox_test.rb
Labels: Pending UAT on Staging :red_circle:

#1306 Jsdependency bump december2022
  client/package-lock.json
  yarn.lock
Labels: deploy-review-app

#1307 [dependencies] JS dependency bump December 2022
  client/package-lock.json
  yarn.lock
Labels: Pending UAT on Staging :red_circle:

#1314 [plugin] timesheet tracker (#1313)
  test/fixtures/api_actions.yml
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/plugins/timesheet_request_plugin_test.rb
Labels: Pending UAT on Staging :red_circle:

#1125 [bug fix] Run Error API actions
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/api_namespace.rb
  app/models/api_resource.rb
  app/sidekiq/fire_api_actions_job.rb
  app/views/comfy/admin/api_actions/index.html.haml
  db/migrate/20220906063031_add_additional_data_to_api_actions.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/fixtures/api_actions.yml
  test/helpers/content_helper_test.rb
  test/models/api_namespace_test.rb
  test/models/api_resource_test.rb
  test/test_helper.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1316 [feature] Uncategorized access should allow API Namespace creation
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/helpers/api_accessibility_helper.rb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/cms/categories/_form.html.haml
  test/controllers/admin/comfy/api_actions_controller_test.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/comfy/cms/categories.yml
  test/helpers/api_accessibility_helper_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1319 [feature] Uncategorized access should allow API Namespace creation
  app/controllers/comfy/admin/api_actions_controller.rb
  app/controllers/subdomains/base_controller.rb
  app/helpers/api_accessibility_helper.rb
  app/views/comfy/admin/api_actions/_form.html.haml
  app/views/comfy/admin/api_actions/action_workflow.html.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/cms/categories/_form.html.haml
  test/controllers/admin/comfy/api_actions_controller_test.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/comfy/cms/categories.yml
  test/helpers/api_accessibility_helper_test.rb
Labels: Pending UAT on Staging :red_circle:

#1322 [bug fix] Run Error API actions
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/api_namespace.rb
  app/models/api_resource.rb
  app/services/api_namespace/plugin/v1/subdomain_events_service.rb
  app/sidekiq/api_resource_spawn_job.rb
  app/sidekiq/fire_api_actions_job.rb
  app/views/comfy/admin/api_actions/index.html.haml
  db/migrate/20220906063031_add_additional_data_to_api_actions.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/controllers/simple_discussion/forum_threads_controller_test.rb
  test/fixtures/api_actions.yml
  test/helpers/content_helper_test.rb
  test/models/api_namespace_test.rb
  test/models/api_resource_test.rb
  test/test_helper.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app
