Repository restarone/violet_rails, pull requests merged in 2022-08, with the labels that each got.

#997 [Bug Fix] Silent recaptcha with challenge if confidence is low
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/shared/fallback_to_recaptcha_v2.js.erb
  test/controllers/resource_controller_test.rb
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#994 [Dev workflow] minimal config for nginx in docker + rails, [Plugin] Create External API Connection that backfills attributes on API Namespace + API Resources
  docker-compose.yml
  nginx.Dockerfile
  nginx.conf
  test/fixtures/external_api_clients.yml
  test/plugins/sync_attribute_to_api_namespace_plugin_test.rb
Labels: Passing UAT on Staging :white_check_mark:, Passing UAT on Heroku :white_check_mark:

#998 [Dev workflow] minimal config for nginx in docker + rails, [Plugin] Create External API Connection that backfills attributes on API Namespace + API Resources
  docker-compose.yml
  nginx.Dockerfile
  nginx.conf
  test/fixtures/external_api_clients.yml
  test/plugins/sync_attribute_to_api_namespace_plugin_test.rb
Labels: release-candidate

#991 [Feature] return non primitive types in REST API and GraphQL response
  app/controllers/api/resource_controller.rb
  app/graphql/types/api_resource_type.rb
  app/graphql/types/non_primitive_property_type.rb
  app/models/non_primitive_property.rb
  app/models/subdomain.rb
  app/serializers/api_namespace_serializer.rb
  app/serializers/api_resource_serializer.rb
  app/serializers/non_primitive_property_serializer.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/api/resource_controller_test.rb
  test/controllers/graphql_controller_test.rb
  test/models/subdomain_test.rb
Labels: Passing UAT on Heroku :white_check_mark:

#1001 [Feature] return non primitive types in REST API and GraphQL response
  app/controllers/api/resource_controller.rb
  app/graphql/types/api_resource_type.rb
  app/graphql/types/non_primitive_property_type.rb
  app/models/non_primitive_property.rb
  app/models/subdomain.rb
  app/serializers/api_namespace_serializer.rb
  app/serializers/api_resource_serializer.rb
  app/serializers/non_primitive_property_serializer.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/api/resource_controller_test.rb
  test/controllers/graphql_controller_test.rb
  test/models/subdomain_test.rb
Labels: Pending UAT on Staging :red_circle:

#662 [Feature] Custom html snippet for flash message (#591)
  app/assets/stylesheets/application.scss
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/models/api_form.rb
  app/models/api_resource.rb
  app/views/comfy/admin/api_forms/_form.html.haml
  app/views/shared/_flash.haml
  app/views/shared/_flash_content.haml
  db/migrate/20220519092534_change_success_message_and_error_message_data_type_to_text.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/models/api_form_test.rb
  test/models/api_resource_test.rb
Labels: high priority, API - data pipeline v3, Passing UAT on Heroku :white_check_mark:

#1002 [Feature] Custom html snippet for flash message
  app/assets/stylesheets/application.scss
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/models/api_form.rb
  app/models/api_resource.rb
  app/views/comfy/admin/api_forms/_form.html.haml
  app/views/shared/_flash.haml
  app/views/shared/_flash_content.haml
  db/migrate/20220519092534_change_success_message_and_error_message_data_type_to_text.rb
  db/schema.rb
  test/controllers/resource_controller_test.rb
  test/models/api_form_test.rb
  test/models/api_resource_test.rb
Labels: Passing UAT on Staging :white_check_mark:

#1008 [feature] branded 404/500 pages (#1007)
  public/404.html
  public/500.html
Labels: Pending UAT on Staging :red_circle:

#979 [Bug Fix] Redirect back if no redirect action is defined
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  test/controllers/resource_controller_test.rb
  test/fixtures/api_namespaces.yml
Labels: Passing UAT on Heroku :white_check_mark:

#1009 [Bug Fix] Redirect back if no redirect action is defined (#979)
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  test/controllers/resource_controller_test.rb
  test/fixtures/api_namespaces.yml
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1010 [feature] Conditional render snippet based on user session
  app/helpers/content_helper.rb
  test/fixtures/comfy/cms/snippets.yml
  test/helpers/content_helper_test.rb
Labels: Pending UAT on Heroku :warning:

#1013 [feature] Conditional render snippet based on user session
  app/helpers/content_helper.rb
  test/fixtures/comfy/cms/snippets.yml
  test/helpers/content_helper_test.rb
Labels: Passing UAT on Staging :white_check_mark:

#1006 [feature] rerender recaptcha if recaptcha verification fails
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/shared/reset_recaptcha_with_error.js.erb
  test/controllers/resource_controller_test.rb
Labels: Failing UAT :x: :skull_and_crossbones:

#1024 [bug fix] handle Recaptcha with turbo
  app/javascript/packs/application.js
  app/views/comfy/admin/api_forms/_render.haml
Labels: Passing UAT on Heroku :white_check_mark:

#1025 [bug fix] handle Recaptcha with turbo
  app/javascript/packs/application.js
  app/views/comfy/admin/api_forms/_render.haml
Labels: Passing UAT on Staging :white_check_mark:

#1026 [feature]: Ability to download CSV of API resources (#1022)
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  config/routes.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/api_resources.yml
Labels: Passing UAT on Heroku :white_check_mark:

#1028 [feature]: Ability to download CSV of API resources (#1022) (#1026)
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  config/routes.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/api_resources.yml
Labels: Pending UAT on Staging :red_circle:

#1031 rerender recaptcha if recaptcha fails
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/views/shared/reset_recaptcha_with_error.js.erb
  test/controllers/resource_controller_test.rb
Labels: Passing UAT on Heroku :white_check_mark:

#1037 [feature] rerender recaptcha if recaptcha fails
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  app/views/shared/reset_recaptcha_with_error.js.erb
  test/controllers/resource_controller_test.rb
Labels: release-candidate

#1027 [feature]: Fire api actions from model (#1012)
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/api_resource.rb
  app/sidekiq/external_api_client_job.rb
  app/sidekiq/fire_api_actions_job.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/resource_controller_test.rb
  test/fixtures/api_actions.yml
  test/fixtures/api_namespaces.yml
  test/fixtures/external_api_clients.yml
  test/models/api_resource_test.rb
  test/models/external_api_client_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
  test/test_helper.rb
Labels: Passing UAT on Heroku :white_check_mark:

#1038 [feature]: Fire api actions from model (#1012) (#1027)
  app/controllers/concerns/api_actionable.rb
  app/models/api_action.rb
  app/models/api_resource.rb
  app/sidekiq/external_api_client_job.rb
  app/sidekiq/fire_api_actions_job.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/resource_controller_test.rb
  test/fixtures/api_actions.yml
  test/fixtures/api_namespaces.yml
  test/fixtures/external_api_clients.yml
  test/models/api_resource_test.rb
  test/models/external_api_client_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
  test/test_helper.rb
Labels: Pending UAT on Staging :red_circle:

#1040 [feature] namespace sidekiq + add queues
  Gemfile
  Gemfile.lock
  config/initializers/sidekiq.rb
  config/sidekiq.yml
Labels: Pending UAT on Staging :red_circle:

#1036 [feature]: Render API Resource file attachment if representable
  app/assets/stylesheets/application.scss
  app/helpers/api_resources_helper.rb
  app/javascript/packs/common.js
  app/views/api_action_mailer/send_email.html.erb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/comfy/admin/api_namespaces/_editor.haml
Labels: Failing UAT :x: :skull_and_crossbones:

#1042 [feature] Render API Resource file attachment if representable
  app/assets/stylesheets/application.scss
  app/helpers/api_resources_helper.rb
  app/javascript/packs/common.js
  app/views/api_action_mailer/send_email.html.erb
  app/views/comfy/admin/api_forms/_render.haml
  app/views/comfy/admin/api_namespaces/_editor.haml
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1053 [feature]: Add categorization to all entities (#1046)
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/cms/categories_controller.rb
  app/controllers/comfy/admin/cms/layouts_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/mailbox/mailbox_controller.rb
  app/controllers/mailbox/message_threads_controller.rb
  app/models/api_namespace.rb
  app/models/comfy/cms/category.rb
  app/models/comfy/cms/layout.rb
  app/models/message_thread.rb
  app/models/user.rb
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/index.html.haml
  app/views/comfy/admin/cms/categories/_edit.html.haml
  app/views/comfy/admin/cms/categories/_form.html.haml
  app/views/comfy/admin/cms/categories/_index.html.haml
  app/views/comfy/admin/cms/categories/_show.html.haml
  app/views/comfy/admin/cms/layouts/_form.html.haml
  app/views/comfy/admin/cms/layouts/_index_branch.html.haml
  app/views/comfy/admin/cms/layouts/index.html.haml
  app/views/comfy/admin/users/_form.haml
  app/views/comfy/admin/users/index.html.haml
  app/views/mailbox/mailbox/show.haml
  app/views/mailbox/message_threads/_add_categories.html.haml
  app/views/mailbox/message_threads/_form.haml
  app/views/mailbox/message_threads/show.haml
  app/views/messages/_form.haml
  config/routes.rb
  db/migrate/20220822163022_remove_required_validation_for_site_in_categories.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/layouts_controller_test.rb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/mailbox/mailbox_controller_test.rb
  test/fixtures/comfy/cms/categories.yml
  test/fixtures/message_threads.yml
Labels: Passing UAT on Heroku :white_check_mark:

#1068 [feature]: Add categorization to all entities
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/cms/categories_controller.rb
  app/controllers/comfy/admin/cms/layouts_controller.rb
  app/controllers/comfy/admin/users_controller.rb
  app/controllers/mailbox/mailbox_controller.rb
  app/controllers/mailbox/message_threads_controller.rb
  app/models/api_namespace.rb
  app/models/comfy/cms/category.rb
  app/models/comfy/cms/layout.rb
  app/models/message_thread.rb
  app/models/user.rb
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/index.html.haml
  app/views/comfy/admin/cms/categories/_edit.html.haml
  app/views/comfy/admin/cms/categories/_form.html.haml
  app/views/comfy/admin/cms/categories/_index.html.haml
  app/views/comfy/admin/cms/categories/_show.html.haml
  app/views/comfy/admin/cms/layouts/_form.html.haml
  app/views/comfy/admin/cms/layouts/_index_branch.html.haml
  app/views/comfy/admin/cms/layouts/index.html.haml
  app/views/comfy/admin/users/_form.haml
  app/views/comfy/admin/users/index.html.haml
  app/views/mailbox/mailbox/show.haml
  app/views/mailbox/message_threads/_add_categories.html.haml
  app/views/mailbox/message_threads/_form.haml
  app/views/mailbox/message_threads/show.haml
  app/views/messages/_form.haml
  config/routes.rb
  db/migrate/20220822163022_remove_required_validation_for_site_in_categories.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/layouts_controller_test.rb
  test/controllers/admin/comfy/users_controller_test.rb
  test/controllers/mailbox/mailbox_controller_test.rb
  test/fixtures/comfy/cms/categories.yml
  test/fixtures/message_threads.yml
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1065 [feature]: Include non primitive types in csv export
  app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Passing UAT on Heroku :white_check_mark:

#1069 [feature] Include non primitive types in csv export
  app/views/comfy/admin/api_namespaces/export_api_resources.csv.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Pending UAT on Staging :red_circle:

#1066 [Bug fix]: API form success flash message randomly showing in admin UI & creating an API resource from admin results in broken page
  app/controllers/comfy/admin/api_resources_controller.rb
  app/controllers/concerns/api_actionable.rb
  app/controllers/resource_controller.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/controllers/resource_controller_test.rb
Labels: Passing UAT on Staging :white_check_mark:, Passing UAT on Heroku :white_check_mark:
