Repository restarone/violet_rails, pull requests merged in 2022-11, with the labels that each got.

#1190 [CI] create separate redis service for the review-apps in dokku-CI
  .github/workflows/dokku-deploy.yml
  bin/ci-pre-deploy
Labels: release-candidate

#1187 [Feature] Social Sharing Metadata Option in API Namespace (#1174)
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/helpers/content_helper.rb
  app/helpers/subdomain_helper.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/shared/_meta_tags.html.erb
  config/routes.rb
  db/migrate/20221025091924_add_metadata_to_api_namespaces.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/helpers/subdomain_helper_test.rb
Labels: deploy-review-app

#1191 [Feature] Social Sharing Metadata Option in API Namespace
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/helpers/content_helper.rb
  app/helpers/subdomain_helper.rb
  app/models/non_primitive_property.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/shared/_meta_tags.html.erb
  config/routes.rb
  db/migrate/20221025091924_add_metadata_to_api_namespaces.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/helpers/subdomain_helper_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, Pending UAT on Staging :red_circle:

#1198 [Feature] Social Sharing Metadata Option in API Namespace (#1191)
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/helpers/content_helper.rb
  app/helpers/subdomain_helper.rb
  app/models/non_primitive_property.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/shared/_meta_tags.html.erb
  config/routes.rb
  db/migrate/20221025091924_add_metadata_to_api_namespaces.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/helpers/subdomain_helper_test.rb
Labels: release-candidate

#1155 [feature] upload file before form submission
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/direct_upload.scss
  app/helpers/api_forms_helper.rb
  app/javascript/packs/common.js
  app/javascript/packs/direct_upload.js
Labels: Passing UAT on Testnet :white_check_mark:

#1200 [feature] upload file before form submission (#1155)
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/direct_upload.scss
  app/helpers/api_forms_helper.rb
  app/javascript/packs/common.js
  app/javascript/packs/direct_upload.js
Labels: Passing UAT on Staging :white_check_mark:

#1201 bugfix:1199 meta tags for views
  app/views/shared/_meta_tags.html.erb
Labels: bug, early-alpha UNSAFE, do not merge

#1182 [feature] 2FA + ability to enforce 2FA at the subdomain level (#1153)
  .env.test
  .github/workflows/ruby.yml
  Gemfile
  Gemfile.lock
  app/controllers/comfy/admin/web_settings_controller.rb
  app/controllers/concerns/twofactor_authenticable.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/mailers/user_mailer.rb
  app/models/subdomain.rb
  app/models/user.rb
  app/views/comfy/admin/web_settings/_form.haml
  app/views/user_mailer/send_otp.html.erb
  app/views/users/invitations/edit.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/sessions/new.html.haml
  app/views/users/sessions/two_factor.html.erb
  app/views/users/shared/error.js.erb
  app/views/users/shared/otp_visible.js.erb
  config/initializers/devise.rb
  config/routes.rb
  config/secrets.yml
  db/migrate/20221010090227_add_devise_two_factor_to_users.rb
  db/migrate/20221010105643_add_enable_2fa_to_subdomains.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users/registrations_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/mailers/user_mailer_test.rb
  test/models/subdomain_test.rb
Labels: enhancement, Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1189 [feature] link to associated CMS entity in API
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/api_namespace.rb
  app/views/comfy/admin/api_namespaces/index.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/models/api_namespace_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1217 [feature] link to associated CMS entity in API (#1189)
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/api_namespace.rb
  app/views/comfy/admin/api_namespaces/index.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/models/api_namespace_test.rb
Labels: Pending UAT on Staging :red_circle:

#1162 [Violet Rails Core]: Prevent raw sql usage in api
  app/models/concerns/safe_executable_validator.rb
  test/fixtures/external_api_clients.yml
  test/models/external_api_client_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1219 [bug fix] cant change/create category in forum
  app/models/forum_category.rb
  test/controllers/simple_discussion/forum_categories_controller_test.rb
Labels: Passing UAT on Testnet :white_check_mark:

#1221 [bug fix] cant change/create category in forum (#1219)
  app/models/forum_category.rb
  test/controllers/simple_discussion/forum_categories_controller_test.rb
Labels: Pending UAT on Staging :red_circle:

#1220 [feature] Prevent raw sql usage in API
  app/models/concerns/safe_executable_validator.rb
  test/fixtures/external_api_clients.yml
  test/models/external_api_client_test.rb
Labels: Passing UAT on Testnet :white_check_mark:

#1222 [feature] Prevent raw SQL usage in API (#1220)
  app/models/concerns/safe_executable_validator.rb
  test/fixtures/external_api_clients.yml
  test/models/external_api_client_test.rb
Labels: Pending UAT on Staging :red_circle:

#1223 [feature] ability to define forum email notification strategy
  app/controllers/comfy/admin/web_settings_controller.rb
  app/mailers/simple_discussion/user_mailer.rb
  app/models/subdomain.rb
  app/views/comfy/admin/web_settings/_form.haml
  db/migrate/20221104133642_add_email_notification_strategy_to_subdomain.rb
  db/schema.rb
  test/mailers/simple_discussion/user_mailer_test.rb
  test/models/subdomain_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1226 [feature] ability to define forum email notification strategy (#1223)
  app/controllers/comfy/admin/web_settings_controller.rb
  app/mailers/simple_discussion/user_mailer.rb
  app/models/subdomain.rb
  app/views/comfy/admin/web_settings/_form.haml
  db/migrate/20221104133642_add_email_notification_strategy_to_subdomain.rb
  db/schema.rb
  test/mailers/simple_discussion/user_mailer_test.rb
  test/models/subdomain_test.rb
Labels: Pending UAT on Staging :red_circle:

#1229 [bug fix] social share meta data mapping (#1227)
  app/helpers/content_helper.rb
  app/helpers/subdomain_helper.rb
  app/views/shared/_meta_tags.html.erb
  test/helpers/subdomain_helper_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1231 bugfix: JS Issue fix after user accepts the cookie consent on Ordinary Trip
  app/views/layouts/comfy/admin/cms/_footer_js.html.haml
Labels: bug, high priority, deploy-review-app

#1230 [bug fix] social share meta data mapping (#1227) (#1229)
  app/helpers/content_helper.rb
  app/helpers/subdomain_helper.rb
  app/views/shared/_meta_tags.html.erb
  test/helpers/subdomain_helper_test.rb
Labels: Pending UAT on Staging :red_circle:

#1216 [feature] 2FA + ability to enforce 2FA in Subdomain
  .env.test
  .github/workflows/ruby.yml
  Gemfile
  Gemfile.lock
  app/controllers/comfy/admin/web_settings_controller.rb
  app/controllers/concerns/twofactor_authenticable.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/mailers/user_mailer.rb
  app/models/subdomain.rb
  app/models/user.rb
  app/views/comfy/admin/web_settings/_form.haml
  app/views/user_mailer/send_otp.html.erb
  app/views/users/invitations/edit.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/sessions/new.html.haml
  app/views/users/sessions/two_factor.html.erb
  app/views/users/shared/error.js.erb
  app/views/users/shared/otp_visible.js.erb
  config/initializers/devise.rb
  config/routes.rb
  config/secrets.yml
  db/migrate/20221010090227_add_devise_two_factor_to_users.rb
  db/migrate/20221010105643_add_enable_2fa_to_subdomains.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users/registrations_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/mailers/user_mailer_test.rb
  test/models/subdomain_test.rb
Labels: Passing UAT on Testnet :white_check_mark:

#1244 [feature] 2FA + ability to enforce 2FA in Subdomain (#1216)
  .env.test
  .github/workflows/ruby.yml
  Gemfile
  Gemfile.lock
  app/controllers/comfy/admin/web_settings_controller.rb
  app/controllers/concerns/twofactor_authenticable.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/mailers/user_mailer.rb
  app/models/subdomain.rb
  app/models/user.rb
  app/views/comfy/admin/web_settings/_form.haml
  app/views/user_mailer/send_otp.html.erb
  app/views/users/invitations/edit.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/sessions/new.html.haml
  app/views/users/sessions/two_factor.html.erb
  app/views/users/shared/error.js.erb
  app/views/users/shared/otp_visible.js.erb
  config/initializers/devise.rb
  config/routes.rb
  config/secrets.yml
  db/migrate/20221010090227_add_devise_two_factor_to_users.rb
  db/migrate/20221010105643_add_enable_2fa_to_subdomains.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users/registrations_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
  test/mailers/user_mailer_test.rb
  test/models/subdomain_test.rb
Labels: deploy-review-app

#1250 [Nikean.org]user cannot sign up when subdomain has 2FA enabled
  app/controllers/users/invitations_controller.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users/registrations_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
Labels: bug, high priority, deploy-review-app

#1252 [feature] Unify form and renderer
  app/views/comfy/admin/api_namespaces/index.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1254 [feature] Unify form and renderer (#1252)
  app/views/comfy/admin/api_namespaces/index.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Pending UAT on Staging :red_circle:

#1192 Ability to mention user in forum
  app/assets/stylesheets/actiontext.scss
  app/controllers/simple_discussion/application_controller.rb
  app/controllers/simple_discussion/forum_posts_controller.rb
  app/controllers/simple_discussion/forum_threads_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/tribute.js
  app/models/forum_post.rb
  app/models/forum_thread.rb
  app/models/user.rb
  app/views/simple_discussion/forum_posts/_form.html.erb
  app/views/simple_discussion/forum_threads/_form.html.erb
  app/views/users/_user.html.erb
  config/locales/en.yml
  package.json
  test/controllers/simple_discussion/forum_threads_controller_test.rb
Labels: Failing UAT :x: :skull_and_crossbones:
