Repository restarone/violet_rails, pull requests merged in 2023-04, with the labels that each got.

#1511 setup strong_migration
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
  db/migrate/20210823235033_add_preview_to_cms_pages.rb
Labels: Passing UAT on Testnet :white_check_mark:

#1514 [feature] install strong_migrations
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
  db/migrate/20210823235033_add_preview_to_cms_pages.rb
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1462 [fix] optimize analytics V2 further + lockdown profiler
  app/controllers/application_controller.rb
  app/controllers/comfy/admin/v2/dashboard_controller.rb
  app/helpers/dashboard_helper.rb
  app/models/ahoy/event.rb
  app/views/comfy/admin/v2/dashboard/_events.html.haml
  app/views/comfy/admin/v2/dashboard/dashboard.html.haml
  config/initializers/strong_migrations.rb
  db/migrate/20230321055733_add_index_to_ahoy_events_name_and_time.rb
  db/schema.rb
  db/seeds.rb
  db/violet_seeds/violet.rb
  test/controllers/admin/comfy/v2/dashboard_controller_test.rb
  test/helpers/dashboard_helper_test.rb
  test/integration/mini_profiler_test.rb
  test/models/ahoy/event_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app, DB-migration

#1522 [fix] optimize analytics V2 further + lockdown profiler
  app/controllers/application_controller.rb
  app/controllers/comfy/admin/v2/dashboard_controller.rb
  app/helpers/dashboard_helper.rb
  app/models/ahoy/event.rb
  app/views/comfy/admin/v2/dashboard/_events.html.haml
  app/views/comfy/admin/v2/dashboard/dashboard.html.haml
  config/initializers/strong_migrations.rb
  db/migrate/20230321055733_add_index_to_ahoy_events_name_and_time.rb
  db/schema.rb
  db/seeds.rb
  db/violet_seeds/violet.rb
  test/controllers/admin/comfy/v2/dashboard_controller_test.rb
  test/helpers/dashboard_helper_test.rb
  test/integration/mini_profiler_test.rb
  test/models/ahoy/event_test.rb
Labels: deploy-review-app, DB-migration

#1523 [fix] optimize analytics V2 further + lockdown profiler
  app/controllers/application_controller.rb
  app/controllers/comfy/admin/v2/dashboard_controller.rb
  app/helpers/dashboard_helper.rb
  app/models/ahoy/event.rb
  app/views/comfy/admin/v2/dashboard/_events.html.haml
  app/views/comfy/admin/v2/dashboard/dashboard.html.haml
  config/initializers/strong_migrations.rb
  db/migrate/20230321055733_add_index_to_ahoy_events_name_and_time.rb
  db/schema.rb
  db/seeds.rb
  db/violet_seeds/violet.rb
  test/controllers/admin/comfy/v2/dashboard_controller_test.rb
  test/helpers/dashboard_helper_test.rb
  test/integration/mini_profiler_test.rb
  test/models/ahoy/event_test.rb
Labels: release-candidate

#1516 style: reduce bit typo misspelling README
  README.md
Labels: documentation

#1518 API namespaces list view
  app/assets/stylesheets/api_namespaces.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/comfy/admin/cms/custom.sass
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/javascript/controllers/api_namespaces_controller.js
  app/javascript/controllers/api_resources_controller.js
  app/javascript/controllers/list_view_controller.js
  app/views/comfy/admin/api_namespaces/_table.html.haml
  app/views/comfy/admin/api_namespaces/api_resources/_index.html.haml
  app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
  app/views/comfy/admin/api_namespaces/index.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1531 [feature] improved API namespaces list view
  app/assets/stylesheets/api_namespaces.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/comfy/admin/cms/custom.sass
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/javascript/controllers/api_namespaces_controller.js
  app/javascript/controllers/api_resources_controller.js
  app/javascript/controllers/list_view_controller.js
  app/views/comfy/admin/api_namespaces/_table.html.haml
  app/views/comfy/admin/api_namespaces/api_resources/_index.html.haml
  app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
  app/views/comfy/admin/api_namespaces/index.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1521 [plugin] for sending report of billables
  app/mailers/e_mailer.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/fixtures/api_actions.yml
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/fixtures/external_api_clients.yml
  test/plugin_fixtures/billables_report_plugin.yml
  test/plugin_fixtures/bishop_monitoring.yml
  test/plugin_fixtures/bishop_tls_monitoring.yml
  test/plugin_fixtures/compliance_visitor_data_request_plugin.yml
  test/plugin_fixtures/dependencies/api_actions/bishop_monitoring_actions.yml
  test/plugin_fixtures/dependencies/api_actions/bishop_tls_monitoring_actions.yml
  test/plugin_fixtures/dependencies/api_actions/timesheet_request_actions.yml
  test/plugin_fixtures/dependencies/api_namespaces/bishop_monitoring_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/bishop_tls_monitoring_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/compliance_visitor_data_request_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/consultant_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/mailchimp_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/time_tracker_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/timesheet_request_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/transcript_parser_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/unique_string_aggregator_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/vacuum_job_namespaces.yml
  test/plugin_fixtures/dependencies/api_resources/bishop_monitoring_resources.yml
  test/plugin_fixtures/dependencies/api_resources/bishop_tls_monitoring_resources.yml
  test/plugin_fixtures/dependencies/api_resources/compliance_visitor_data_request_resources.yml
  test/plugin_fixtures/dependencies/api_resources/consultant_resources.yml
  test/plugin_fixtures/dependencies/api_resources/mailchimp_resources.yml
  test/plugin_fixtures/dependencies/api_resources/time_tracker_resources.yml
  test/plugin_fixtures/dependencies/api_resources/timesheet_request_resources.yml
  test/plugin_fixtures/dependencies/api_resources/transcript_parser_resources.yml
  test/plugin_fixtures/dependencies/api_resources/vacuum_job_resources.yml
  test/plugin_fixtures/sync_attribute_to_api_namespace.yml
  test/plugin_fixtures/sync_to_mailchimp.yml
  test/plugin_fixtures/transcript_parser_plugin.yml
  test/plugin_fixtures/unique_string_aggregator_plugin.yml
  test/plugin_fixtures/vacuum_job.yml
  test/plugins/billables_report_plugin_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
  test/plugins/compliance_visitor_data_request_plugin_test.rb
  test/plugins/unique_string_aggregator_plugin_test.rb
  test/plugins/vacuum_job_plugin_test.rb
Labels: Passing UAT on Staging :white_check_mark:

#1543 [plugin] for sending report of billables
  app/mailers/e_mailer.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/fixtures/api_actions.yml
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/fixtures/external_api_clients.yml
  test/plugin_fixtures/billables_report_plugin.yml
  test/plugin_fixtures/bishop_monitoring.yml
  test/plugin_fixtures/bishop_tls_monitoring.yml
  test/plugin_fixtures/compliance_visitor_data_request_plugin.yml
  test/plugin_fixtures/dependencies/api_actions/bishop_monitoring_actions.yml
  test/plugin_fixtures/dependencies/api_actions/bishop_tls_monitoring_actions.yml
  test/plugin_fixtures/dependencies/api_actions/timesheet_request_actions.yml
  test/plugin_fixtures/dependencies/api_namespaces/bishop_monitoring_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/bishop_tls_monitoring_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/compliance_visitor_data_request_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/consultant_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/mailchimp_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/time_tracker_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/timesheet_request_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/transcript_parser_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/unique_string_aggregator_namespaces.yml
  test/plugin_fixtures/dependencies/api_namespaces/vacuum_job_namespaces.yml
  test/plugin_fixtures/dependencies/api_resources/bishop_monitoring_resources.yml
  test/plugin_fixtures/dependencies/api_resources/bishop_tls_monitoring_resources.yml
  test/plugin_fixtures/dependencies/api_resources/compliance_visitor_data_request_resources.yml
  test/plugin_fixtures/dependencies/api_resources/consultant_resources.yml
  test/plugin_fixtures/dependencies/api_resources/mailchimp_resources.yml
  test/plugin_fixtures/dependencies/api_resources/time_tracker_resources.yml
  test/plugin_fixtures/dependencies/api_resources/timesheet_request_resources.yml
  test/plugin_fixtures/dependencies/api_resources/transcript_parser_resources.yml
  test/plugin_fixtures/dependencies/api_resources/vacuum_job_resources.yml
  test/plugin_fixtures/sync_attribute_to_api_namespace.yml
  test/plugin_fixtures/sync_to_mailchimp.yml
  test/plugin_fixtures/transcript_parser_plugin.yml
  test/plugin_fixtures/unique_string_aggregator_plugin.yml
  test/plugin_fixtures/vacuum_job.yml
  test/plugins/billables_report_plugin_test.rb
  test/plugins/bishop_monitoring_plugin_test.rb
  test/plugins/bishop_tls_monitoring_plugin_test.rb
  test/plugins/compliance_visitor_data_request_plugin_test.rb
  test/plugins/unique_string_aggregator_plugin_test.rb
  test/plugins/vacuum_job_plugin_test.rb
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1542 [feature] Turbo Drive and Sessions in iOS
  .env.development
  app/assets/javascripts/comfy/admin/cms/custom.js
  app/controllers/concerns/twofactor_authenticable.rb
  app/controllers/users/otp/sessions_controller.rb
  app/controllers/users/sessions_controller.rb
  app/javascript/packs/comfy/admin/cms.js
  app/javascript/packs/turbo.js
  app/views/admin/subdomain_requests/edit.html.haml
  app/views/admin/subdomain_requests/index.html.haml
  app/views/admin/subdomain_requests/show.html.haml
  app/views/admin/subdomain_requests/update.html.haml
  app/views/admin/subdomains/edit.html.haml
  app/views/admin/subdomains/index.html.haml
  app/views/admin/subdomains/new.html.haml
  app/views/admin/subdomains/show.html.haml
  app/views/admin/subdomains/update.html.haml
  app/views/admin/web_console/index.html.haml
  app/views/comfy/admin/api_namespaces/_editor.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/api_resources/_form.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  app/views/comfy/admin/cms/partials/_navigation_inner.haml
  app/views/comfy/admin/dashboard/events_detail.html.haml
  app/views/comfy/admin/dashboard/events_list.html.haml
  app/views/comfy/admin/dashboard/visit.html.haml
  app/views/comfy/admin/external_api_clients/_form.html.haml
  app/views/comfy/admin/external_api_clients/show.html.haml
  app/views/comfy/admin/users/edit.html.haml
  app/views/comfy/admin/users/new.html.haml
  app/views/comfy/admin/web_settings/edit.html.haml
  app/views/layouts/comfy/admin/cms/_body.html.haml
  app/views/layouts/devise.html.haml
  app/views/mailbox/mailbox/show.html.haml
  app/views/mailbox/message_threads/new.html.haml
  app/views/mailbox/message_threads/show.html.haml
  app/views/shared/_flash_content.haml
  app/views/simple_discussion/forum_categories/new.html.haml
  app/views/users/confirmations/new.html.haml
  app/views/users/otp/sessions/new.html.haml
  app/views/users/passwords/new.html.haml
  app/views/users/registrations/new.html.haml
  app/views/users/sessions/new.html.haml
  app/views/users/sessions/two_factor.html.erb
  app/views/users/sessions/two_factor.html.haml
  app/views/users/shared/_links.html.erb
  app/views/users/unlocks/new.html.haml
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  lib/devise-two-factor/strategies/otp_attempt_authenticatable.rb
  test/controllers/users/otp/sessions_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1547 [feature] Turbo Drive and Sessions in iOS (#1542)
  .env.development
  app/assets/javascripts/comfy/admin/cms/custom.js
  app/controllers/concerns/twofactor_authenticable.rb
  app/controllers/users/otp/sessions_controller.rb
  app/controllers/users/sessions_controller.rb
  app/javascript/packs/comfy/admin/cms.js
  app/javascript/packs/turbo.js
  app/views/admin/subdomain_requests/edit.html.haml
  app/views/admin/subdomain_requests/index.html.haml
  app/views/admin/subdomain_requests/show.html.haml
  app/views/admin/subdomain_requests/update.html.haml
  app/views/admin/subdomains/edit.html.haml
  app/views/admin/subdomains/index.html.haml
  app/views/admin/subdomains/new.html.haml
  app/views/admin/subdomains/show.html.haml
  app/views/admin/subdomains/update.html.haml
  app/views/admin/web_console/index.html.haml
  app/views/comfy/admin/api_namespaces/_editor.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/api_resources/_form.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  app/views/comfy/admin/cms/partials/_navigation_inner.haml
  app/views/comfy/admin/dashboard/events_detail.html.haml
  app/views/comfy/admin/dashboard/events_list.html.haml
  app/views/comfy/admin/dashboard/visit.html.haml
  app/views/comfy/admin/external_api_clients/_form.html.haml
  app/views/comfy/admin/external_api_clients/show.html.haml
  app/views/comfy/admin/users/edit.html.haml
  app/views/comfy/admin/users/new.html.haml
  app/views/comfy/admin/web_settings/edit.html.haml
  app/views/layouts/comfy/admin/cms/_body.html.haml
  app/views/layouts/devise.html.haml
  app/views/mailbox/mailbox/show.html.haml
  app/views/mailbox/message_threads/new.html.haml
  app/views/mailbox/message_threads/show.html.haml
  app/views/shared/_flash_content.haml
  app/views/simple_discussion/forum_categories/new.html.haml
  app/views/users/confirmations/new.html.haml
  app/views/users/otp/sessions/new.html.haml
  app/views/users/passwords/new.html.haml
  app/views/users/registrations/new.html.haml
  app/views/users/sessions/new.html.haml
  app/views/users/sessions/two_factor.html.erb
  app/views/users/sessions/two_factor.html.haml
  app/views/users/shared/_links.html.erb
  app/views/users/unlocks/new.html.haml
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  lib/devise-two-factor/strategies/otp_attempt_authenticatable.rb
  test/controllers/users/otp/sessions_controller_test.rb
  test/controllers/users/sessions_controller_test.rb
Labels: release-candidate
