Repository restarone/violet_rails, pull requests merged in 2023-05, with the labels that each got.

#1555 API namespace associations
  app/assets/stylesheets/api_namespaces.scss
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/models/api_namespace.rb
  app/models/api_resource.rb
  app/models/external_api_client.rb
  app/views/comfy/admin/api_namespaces/_association_form.html.haml
  app/views/comfy/admin/api_namespaces/_associations.html.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  db/migrate/20230516012035_add_associations_to_api_namespace.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/models/api_namespace_test.rb
  test/models/api_resource_test.rb
Labels: early-alpha UNSAFE, Pending UAT on Testnet :warning:, deploy-review-app

#1556 [feature] API Namespace Associations, update README
  README.md
  app/assets/stylesheets/api_namespaces.scss
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/controllers/comfy/admin/api_resources_controller.rb
  app/models/api_namespace.rb
  app/models/api_resource.rb
  app/models/external_api_client.rb
  app/views/comfy/admin/api_namespaces/_association_form.html.haml
  app/views/comfy/admin/api_namespaces/_associations.html.haml
  app/views/comfy/admin/api_namespaces/_form.html.haml
  app/views/comfy/admin/api_namespaces/api_resources/_table.html.haml
  app/views/comfy/admin/api_namespaces/show.html.haml
  app/views/comfy/admin/api_resources/show.html.haml
  db/migrate/20230516012035_add_associations_to_api_namespace.rb
  db/schema.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/models/api_namespace_test.rb
  test/models/api_resource_test.rb
Labels: release-candidate

#1560 [feature]: include geolocation in cookies metadata hash
  app/controllers/cookies_controller.rb
  config/initializers/geocoder.rb
  test/controllers/cookies_controller_test.rb
  test/tasks/fill_empty_location_entries_task_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1564 [feature] include geolocation in cookies metadata hash
  app/controllers/cookies_controller.rb
  config/initializers/geocoder.rb
  test/controllers/cookies_controller_test.rb
  test/tasks/fill_empty_location_entries_task_test.rb
Labels: release-candidate

#1558 [bug fix] Webhook race condition
  app/controllers/api/external_api_clients_controller.rb
  app/models/external_api_client.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/controllers/api/external_api_clients_controller_test.rb
  test/models/external_api_client_test.rb
Labels: early-alpha UNSAFE, Pending UAT on Testnet :warning:

#1565 [bug fix] Webhook race condition
  app/controllers/api/external_api_clients_controller.rb
  app/models/external_api_client.rb
  test/controllers/admin/comfy/external_api_clients_controller_test.rb
  test/controllers/api/external_api_clients_controller_test.rb
  test/models/external_api_client_test.rb
Labels: release-candidate
