Repository restarone/violet_rails, pull requests merged in 2023-08, with the labels that each got.

#1581 Email bug fixes august 2023
  app/controllers/mailbox/mailbox_controller.rb
  app/controllers/mailbox/message_threads_controller.rb
  app/helpers/content_helper.rb
  app/mailboxes/e_mailbox.rb
  app/views/mailbox/mailbox/show.html.haml
  app/views/mailbox/message_threads/_index.haml
  db/seeds.rb
  test/controllers/mailbox/mailbox_controller_test.rb
  test/controllers/mailbox/message_threads_controller_test.rb
  test/mailboxes/e_mailbox_test.rb
Labels: deploy-review-app

#1584 [WIP] fix(): thread order
  app/controllers/mailbox/mailbox_controller.rb
  test/controllers/mailbox/mailbox_controller_test.rb
Labels: WIP, do not merge

#1582 Email bug fixes august 2023 (#1581)
  app/controllers/mailbox/mailbox_controller.rb
  app/controllers/mailbox/message_threads_controller.rb
  app/helpers/content_helper.rb
  app/mailboxes/e_mailbox.rb
  app/views/mailbox/mailbox/show.html.haml
  app/views/mailbox/message_threads/_index.haml
  db/seeds.rb
  test/controllers/mailbox/mailbox_controller_test.rb
  test/controllers/mailbox/message_threads_controller_test.rb
  test/mailboxes/e_mailbox_test.rb
Labels: Passing UAT on Staging :white_check_mark:

#1589 scaffold renderer at API Namespace creation
  .gitignore
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/api_namespace.rb
  app/views/comfy/admin/api_namespaces/_form.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/plugin_fixtures/sync_attribute_to_api_namespace.yml
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1592 [feature] scaffold renderer at API Namespace creation
  .gitignore
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/models/api_namespace.rb
  app/views/comfy/admin/api_namespaces/_form.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/controllers/admin/comfy/api_resources_controller_test.rb
  test/plugin_fixtures/sync_attribute_to_api_namespace.yml
Labels: Pending UAT on Staging :red_circle:

#1557 [Plugin] Printify/Stripe integration
  app/models/api_resource.rb
  app/models/external_api_client.rb
  plugins/installers/printify_stripe_e_commerce.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/fixtures/external_api_clients.yml
  test/integration/mini_profiler_test.rb
  test/models/api_namespace_test.rb
  test/models/api_resource_test.rb
  test/plugin_fixtures/clean_unprocessed_orders.yml
  test/plugin_fixtures/clean_unprocessed_orders_manually.yml
  test/plugin_fixtures/create_order_and_stripe_chekout_session.yml
  test/plugin_fixtures/dependencies/api_namespaces/order_cleanup_logs.yml
  test/plugin_fixtures/dependencies/api_namespaces/orders.yml
  test/plugin_fixtures/dependencies/api_namespaces/printify_accounts.yml
  test/plugin_fixtures/dependencies/api_namespaces/products.yml
  test/plugin_fixtures/dependencies/api_namespaces/shop_logs.yml
  test/plugin_fixtures/dependencies/api_namespaces/shops.yml
  test/plugin_fixtures/dependencies/api_resources/orders_resources.yml
  test/plugin_fixtures/dependencies/api_resources/printify_account_resources.yml
  test/plugin_fixtures/dependencies/api_resources/products_resources.yml
  test/plugin_fixtures/dependencies/api_resources/shops_resources.yml
  test/plugin_fixtures/fetch_printify_shipping_and_stripe_processing_fees.yml
  test/plugin_fixtures/publish_succeed.yml
  test/plugin_fixtures/shops_detail.yml
  test/plugin_fixtures/sync_printify_products.yml
  test/plugin_fixtures/sync_printify_shops.yml
  test/plugins/clean_unprocessed_orders_manually_test.rb
  test/plugins/clean_unprocessed_orders_test.rb
  test/plugins/create_order_and_stripe_chekout_session_test.rb
  test/plugins/fetch_printify_shipping_and_processing_fees_test.rb
  test/plugins/installers/printify_stripe_e_commerce_test.rb
  test/plugins/publish_succeed_plugin_test.rb
  test/plugins/shops_detail_test.rb
  test/plugins/sync_printify_products_plugin_test.rb
  test/plugins/sync_printify_shops_test.rb
  test/tasks/external_api_client_cron_job_test.rb
Labels: Pending UAT on Testnet :warning:, deploy-review-app

#1593 [Plugin] Printify/Stripe integration
  app/models/api_resource.rb
  app/models/external_api_client.rb
  plugins/installers/printify_stripe_e_commerce.rb
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
  test/fixtures/api_namespaces.yml
  test/fixtures/api_resources.yml
  test/fixtures/external_api_clients.yml
  test/integration/mini_profiler_test.rb
  test/models/api_namespace_test.rb
  test/models/api_resource_test.rb
  test/plugin_fixtures/clean_unprocessed_orders.yml
  test/plugin_fixtures/clean_unprocessed_orders_manually.yml
  test/plugin_fixtures/create_order_and_stripe_chekout_session.yml
  test/plugin_fixtures/dependencies/api_namespaces/order_cleanup_logs.yml
  test/plugin_fixtures/dependencies/api_namespaces/orders.yml
  test/plugin_fixtures/dependencies/api_namespaces/printify_accounts.yml
  test/plugin_fixtures/dependencies/api_namespaces/products.yml
  test/plugin_fixtures/dependencies/api_namespaces/shop_logs.yml
  test/plugin_fixtures/dependencies/api_namespaces/shops.yml
  test/plugin_fixtures/dependencies/api_resources/orders_resources.yml
  test/plugin_fixtures/dependencies/api_resources/printify_account_resources.yml
  test/plugin_fixtures/dependencies/api_resources/products_resources.yml
  test/plugin_fixtures/dependencies/api_resources/shops_resources.yml
  test/plugin_fixtures/fetch_printify_shipping_and_stripe_processing_fees.yml
  test/plugin_fixtures/publish_succeed.yml
  test/plugin_fixtures/shops_detail.yml
  test/plugin_fixtures/sync_printify_products.yml
  test/plugin_fixtures/sync_printify_shops.yml
  test/plugins/clean_unprocessed_orders_manually_test.rb
  test/plugins/clean_unprocessed_orders_test.rb
  test/plugins/create_order_and_stripe_chekout_session_test.rb
  test/plugins/fetch_printify_shipping_and_processing_fees_test.rb
  test/plugins/installers/printify_stripe_e_commerce_test.rb
  test/plugins/publish_succeed_plugin_test.rb
  test/plugins/shops_detail_test.rb
  test/plugins/sync_printify_products_plugin_test.rb
  test/plugins/sync_printify_shops_test.rb
  test/tasks/external_api_client_cron_job_test.rb
Labels: Pending UAT on Staging :red_circle:
