Repository restarone/violet_rails, pull requests merged in 2023-02, with the labels that each got.

#1400 [bug fix] Cannot change account email from user settings
  app/models/subdomain.rb
  app/views/shared/_company_logo.haml
  app/views/users/mailer/confirmation_instructions.html.haml
  config/sitemap.rb
  test/controllers/users/registrations_controller_test.rb
  test/models/subdomain_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1398 [Bug Fix]: CMS association not detected when API form is rendered
  app/models/api_namespace.rb
  test/models/api_namespace_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1408 [Bug Fix] CMS association not detected when API form is rendered (#1405)
  app/models/api_namespace.rb
  test/models/api_namespace_test.rb
Labels: Passing UAT on Staging :white_check_mark:, release-candidate

#1411 Brakeman Version Update
  .github/workflows/brakeman-analysis.yml
Labels: high priority

#1413 enable turbo for sign in
  app/views/users/sessions/new.html.haml
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1402 Integration of rack-timeout for limiting request time
  .env.test
  Gemfile
  Gemfile.lock
  config/initializers/rack_timeout.rb
  test/integration/rack_timeout_test.rb
Labels: bug, Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1422 rake timeout duration incrementation
  config/initializers/rack_timeout.rb
Labels: high priority

#1417 purge unattached active storage blob
  config/schedule.rb
  lib/tasks/active_storage.rake
  test/tasks/purge_unattached_task_test.rb
Labels: deploy-review-app

#1423 [feature] purge unattached active storage blob
  config/schedule.rb
  lib/tasks/active_storage.rake
  test/tasks/purge_unattached_task_test.rb
Labels: release-candidate

#1364 [bugfix] dynamic property render in snippets
  Gemfile
  Gemfile.lock
  app/controllers/comfy/admin/api_namespaces_controller.rb
  app/views/comfy/admin/api_namespaces/show.html.haml
  test/controllers/admin/comfy/api_namespaces_controller_test.rb
Labels: Passing UAT on Testnet :white_check_mark:, deploy-review-app

#1426 feat: cms tag 3.5
  Gemfile
  Gemfile.lock
Labels: high priority

#1428 [feature] add rack timeout
  .env.test
  Gemfile
  Gemfile.lock
  config/initializers/rack_timeout.rb
  test/integration/rack_timeout_test.rb
Labels: deploy-review-app

#1429 [feature] add rack timeout (#1428)
  .env.test
  Gemfile
  Gemfile.lock
  config/initializers/rack_timeout.rb
  test/integration/rack_timeout_test.rb
Labels: release-candidate
